name: Test pyinstaller build
on: push
jobs:
    pyinstaller-build:
        name: Build simple application
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - run: git fetch --prune --unshallow

            - name: Fetch git tags
              run: git fetch origin +refs/tags/*:refs/tags/*

            - name: Set up conda
              uses: goanpeca/setup-miniconda@v1.1.2
                  auto-update-conda: true
                  python-version: 3.7
                  channels: conda-forge

            - name: Build env w/dependencies
              shell: bash -l {0}
              run: |
                  conda env update --file environment.yml

